//! Resource modules

pub mod info_type;
pub use info_type::Info_type;
pub mod job_trigger;
pub use job_trigger::Job_trigger;
pub mod project_data_profile;
pub use project_data_profile::Project_data_profile;
pub mod column_data_profile;
pub use column_data_profile::Column_data_profile;
pub mod file_store_data_profile;
pub use file_store_data_profile::File_store_data_profile;
pub mod discovery_config;
pub use discovery_config::Discovery_config;
pub mod deidentify_template;
pub use deidentify_template::Deidentify_template;
pub mod image;
pub use image::Image;
pub mod inspect_template;
pub use inspect_template::Inspect_template;
pub mod stored_info_type;
pub use stored_info_type::Stored_info_type;
pub mod table_data_profile;
pub use table_data_profile::Table_data_profile;
pub mod dlp_job;
pub use dlp_job::Dlp_job;
pub mod content;
pub use content::Content;
pub mod connection;
pub use connection::Connection;

