//! Resource modules

pub mod environment;
pub use environment::Environment;
pub mod destination;
pub use destination::Destination;
pub mod workspace;
pub use workspace::Workspace;
pub mod client;
pub use client::Client;
pub mod trigger;
pub use trigger::Trigger;
pub mod user_permission;
pub use user_permission::User_permission;
pub mod gtag_config;
pub use gtag_config::Gtag_config;
pub mod template;
pub use template::Template;
pub mod zone;
pub use zone::Zone;
pub mod built_in_variable;
pub use built_in_variable::Built_in_variable;
pub mod variable;
pub use variable::Variable;
pub mod version;
pub use version::Version;
pub mod folder;
pub use folder::Folder;
pub mod version_header;
pub use version_header::Version_header;
pub mod container;
pub use container::Container;
pub mod transformation;
pub use transformation::Transformation;
pub mod account;
pub use account::Account;
pub mod tag;
pub use tag::Tag;

