//! Resource modules

pub mod deal;
pub use deal::Deal;
pub mod auction_package;
pub use auction_package::Auction_package;
pub mod publisher_profile;
pub use publisher_profile::Publisher_profile;
pub mod client;
pub use client::Client;
pub mod proposal;
pub use proposal::Proposal;
pub mod user;
pub use user::User;
pub mod finalized_deal;
pub use finalized_deal::Finalized_deal;
pub mod user;
pub use user::User;
pub mod proposal;
pub use proposal::Proposal;
pub mod finalized_deal;
pub use finalized_deal::Finalized_deal;
pub mod data_segment;
pub use data_segment::Data_segment;
pub mod client;
pub use client::Client;
pub mod deal;
pub use deal::Deal;
pub mod auction_package;
pub use auction_package::Auction_package;
pub mod publisher_profile;
pub use publisher_profile::Publisher_profile;
pub mod data_segment;
pub use data_segment::Data_segment;

