//! Resource modules

pub mod glossarie;
pub use glossarie::Glossarie;
pub mod location;
pub use location::Location;
pub mod operation;
pub use operation::Operation;
pub mod project;
pub use project::Project;
pub mod detection;
pub use detection::Detection;
pub mod translation;
pub use translation::Translation;
pub mod language;
pub use language::Language;
pub mod project;
pub use project::Project;
pub mod adaptive_mt_sentence;
pub use adaptive_mt_sentence::Adaptive_mt_sentence;
pub mod dataset;
pub use dataset::Dataset;
pub mod example;
pub use example::Example;
pub mod glossary_entrie;
pub use glossary_entrie::Glossary_entrie;
pub mod operation;
pub use operation::Operation;
pub mod adaptive_mt_dataset;
pub use adaptive_mt_dataset::Adaptive_mt_dataset;
pub mod glossarie;
pub use glossarie::Glossarie;
pub mod location;
pub use location::Location;
pub mod adaptive_mt_file;
pub use adaptive_mt_file::Adaptive_mt_file;
pub mod model;
pub use model::Model;

