//! Resource modules

pub mod backend;
pub use backend::Backend;
pub mod domain;
pub use domain::Domain;
pub mod location;
pub use location::Location;
pub mod build;
pub use build::Build;
pub mod rollout;
pub use rollout::Rollout;
pub mod traffic;
pub use traffic::Traffic;
pub mod operation;
pub use operation::Operation;
pub mod backend;
pub use backend::Backend;
pub mod build;
pub use build::Build;
pub mod domain;
pub use domain::Domain;
pub mod location;
pub use location::Location;
pub mod rollout;
pub use rollout::Rollout;
pub mod operation;
pub use operation::Operation;
pub mod traffic;
pub use traffic::Traffic;

