//! Invoice resource
//!
//! Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a "Partner" invoice level are not retrievable through this method.

use crate::{ProviderError, Result};
use std::collections::HashMap;

/// Invoice resource handler
pub struct Invoice<'a> {
    provider: &'a crate::GcpProvider,
}

impl<'a> Invoice<'a> {
    pub(crate) fn new(provider: &'a crate::GcpProvider) -> Self {
        Self { provider }
    }




    /// Read/describe a invoice
    ///
    /// TODO: Map `id` parameter to appropriate SDK field(s)
    #[allow(unused_variables)]
    pub async fn read(&self, id: &str) -> Result<()> {

        todo!("Implement read for Gcp")

    }





}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_invoice_operations() {
        // Test invoice CRUD operations
    }
}
